[workspace]
resolver = "2"
members = ["crates/slimg-core", "crates/slimg-ffi", "crates/libjxl-enc-sys", "cli"]

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
