[target.aarch64-unknown-linux-gnu]
pre-build = ["apt-get update && apt-get install -y meson ninja-build nasm git"]

[target.aarch64-unknown-linux-gnu.env]
passthrough = ["SYSTEM_DEPS_DAV1D_BUILD_INTERNAL"]
