[package]
name = "slimg"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Image optimization CLI â€” convert, optimize, resize"

[dependencies]
slimg-core = { path = "../crates/slimg-core" }
clap = { version = "4.5", features = ["derive"] }
clap_complete = "4.5"
anyhow = "1"
