- name: Add NASM to PATH (Windows)
  if: runner.os == 'Windows'
  shell: bash
  run: echo C:/Program Files/NASM >> $GITHUB_PATH

- name: Set dav1d build-from-source flag
  shell: bash
  run: echo "SYSTEM_DEPS_DAV1D_BUILD_INTERNAL=always" >> $GITHUB_ENV
